[RobotSimu] Expose class in python.
stack-of-tasks/sot-core pull request #186
Opened 2021-06-24 13:12 UTC by florent-lamiraux

2021-06-24 13:43 UTC, nim65s requested changes
Hi @florent-lamiraux,

```python
from dynamic_graph.sot.core.robot_simu import RobotSimu
```

Is already working for me. Could you detail a bit more what is not working for you ? Maybe by adding an unit test showing what you want to achieve ?

This class is not already in https://github.com/stack-of-tasks/sot-core/blob/master/tests/python/python_imports.py, so we should probably start by adding it there, but as this is already working we might want to go further to understand this PR.

Looking at #185, I think just a `self.assertTrue(hasattr(RobotSimu(), 'after'))` would do the job :)
Do you want me to add this ?


On another topic, python modules are build from either a `*-python-module-py.cc` or a `*-python.h`. This entity was using `robot-simu-python.h` before, so if you add `robot-simu-python-module-py.cc`, you should remove the header.

Ref: https://github.com/stack-of-tasks/sot-core/blob/aba69263f2653920daeb00efcefff50d44b30c93/src/CMakeLists.txt#L112

2021-06-24 13:43 UTC, nim65s commented on src/tools/robot-simu-python-module-py.cc
> +    reference_existing_object;
What is this for ?

2021-06-24 13:43 UTC, nim65s commented on src/tools/robot-simu-python-module-py.cc
> +  bp::import("dynamic_graph.sot.core.wrap");
Other modules just need `bp::import("dynamic_graph");` ; why is it different here ?

2021-06-24 13:48 UTC, nim65s commented on src/tools/robot-simu-python-module-py.cc
> +#include <sot/core/flags.hh>
I think we only need `dynamic-graph/python/module.hh` & `sot/core/robot-simu.hh`

2021-06-24 13:49 UTC, nim65s commented on src/tools/robot-simu-python-module-py.cc
> +				     bp::bases<dg::sot::Device> >();
```suggestion
  dg::python::exposeEntity<dgs::RobotSimu, bp::bases<dg::sot::Device> >();
```

2021-06-25 09:44 UTC, florent-lamiraux commented
@nim65s : thank you for your feedback. After reinstalling the package, I am not able to reproduce the issue.
I will therefore close this pull request.

2021-06-25 09:44 UTC, closed without merging